...

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -57,19 +57,19 @@ jobs:
       #     done
       #     echo "Containers can reach each other!"
 
-      - name: Check if localhost is accessible
-        run: |
-          retries=30
-          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q 200; do
-            echo "Waiting for localhost to be accessible..."
-            sleep 5
-            retries=$((retries - 1))
-            if [ $retries -le 0 ]; then
-              echo "Localhost is not accessible. Exiting."
-              exit 1
-            fi
-          done
-          echo "Localhost is accessible!"
+      # - name: Check if localhost is accessible
+      #   run: |
+      #     retries=30
+      #     while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q 200; do
+      #       echo "Waiting for localhost to be accessible..."
+      #       sleep 5
+      #       retries=$((retries - 1))
+      #       if [ $retries -le 0 ]; then
+      #         echo "Localhost is not accessible. Exiting."
+      #         exit 1
+      #       fi
+      #     done
+      #     echo "Localhost is accessible!"
 
 
       - name: Install newman
